import type { SdegenToken } from '@/types/token';

export const SDEGEN_TOKENS: SdegenToken[] = [
  {
    id: 'sdg-1-akmis',
    symbol: 'AKMIS',
    name: 'Anak Kos Miskin',
    sdgNumber: 1,
    sdgName: 'No Poverty',
    emoji: '💸',
    imagePath: '/tokens/akmis.png',
    category: 'SURVIVAL',
    monsterName: 'MieMiskinmon',
    monsterConcept: 'tiny instant-noodle cup creature with messy noodle hair, empty wallet, broke survival energy',
    iconPrompt: 'original cute collectible monster mascot, tiny instant-noodle cup creature, messy noodle hair, empty wallet, broke survival energy, cyberpunk meme style',
    memeNarrative: 'makan mie 3x sehari, still buying 💀',
    description: 'broke but active. survival mode ON. maybe this fixes nothing.',
    acronym: 'Access for Komunitas Marginal & Inclusive Sustainability',
    mintAddress: 'REPLACE_WITH_AKMIS_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_AKMIS',
    requiredBalance: 1,
    accentColor: '#E5243B',
    featureTitle: 'Survival Starter Pack',
    featureDescription: 'Basic Impactory access for survival-mode builders.',
  },
  {
    id: 'sdg-2-nasinangis',
    symbol: 'NASINANGIS',
    name: 'Nasi Nangis',
    sdgNumber: 2,
    sdgName: 'Zero Hunger',
    emoji: '🍚',
    imagePath: '/tokens/nasinangis.png',
    category: 'SURVIVAL',
    monsterName: 'RiceCrymon',
    monsterConcept: 'living rice packet creature with rice-grain tears and bent spoon',
    iconPrompt: 'original cute collectible monster mascot, living rice packet creature, rice-grain tears, bent spoon, expressive meme style',
    memeNarrative: 'makan sambil overthinking',
    description: 'not full, but still alive. still aping.',
    acronym: 'Nutrition Access & Sustainable Inclusive Network for Growth',
    mintAddress: 'REPLACE_WITH_NASINANGIS_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_NASINANGIS',
    requiredBalance: 1,
    accentColor: '#DDA63A',
    featureTitle: 'Food Security Insight',
    featureDescription: 'Lightweight food security and local resource storytelling tool.',
  },
  {
    id: 'sdg-3-sehatga',
    symbol: 'SEHATGA',
    name: 'Sehat Gak',
    sdgNumber: 3,
    sdgName: 'Good Health and Well-being',
    emoji: '💊',
    imagePath: '/tokens/sehatga.png',
    category: 'SURVIVAL',
    monsterName: 'BufferBug',
    monsterConcept: 'small green wellness bug with thermometer, bandage, and loading eyes',
    iconPrompt: 'original cute collectible monster mascot, small green wellness bug, thermometer, bandage, loading eyes, soft cyberpunk glow',
    memeNarrative: 'physically here, mentally buffering',
    description: 'checkup pending. vibes unstable. token acquired.',
    acronym: 'System for Equitable Health Access & Transformation',
    mintAddress: 'REPLACE_WITH_SEHATGA_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_SEHATGA',
    requiredBalance: 1,
    accentColor: '#4C9F38',
    featureTitle: 'Wellness Signal Check',
    featureDescription: 'A simple reflection tool for health, burnout, and wellbeing campaigns.',
  },
  {
    id: 'sdg-4-gabisabaca',
    symbol: 'GABISABACA',
    name: 'Gak Bisa Baca',
    sdgNumber: 4,
    sdgName: 'Quality Education',
    emoji: '🎓',
    imagePath: '/tokens/gabisabaca.png',
    category: 'SURVIVAL',
    monsterName: 'BookBlurp',
    monsterConcept: 'confused living book creature with scrambled floating letters',
    iconPrompt: 'original cute collectible monster mascot, confused living book creature, scrambled floating letters, anxious funny face',
    memeNarrative: 'bukan gak mampu, cuma bingung',
    description: 'skill issue or system issue? we may never know.',
    acronym: 'Global Access for Basic Inclusive Skills & Awareness',
    mintAddress: 'REPLACE_WITH_GABISABACA_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_GABISABACA',
    requiredBalance: 1,
    accentColor: '#C5192D',
    featureTitle: 'Learning Prompt Pack',
    featureDescription: 'Education-focused content and learning campaign helper.',
  },
  {
    id: 'sdg-5-sama2capek',
    symbol: 'SAMA2CAPEK',
    name: 'Sama Sama Capek',
    sdgNumber: 5,
    sdgName: 'Gender Equality',
    emoji: '💅',
    imagePath: '/tokens/sama2capek.png',
    category: 'SURVIVAL',
    monsterName: 'CapekDuo',
    monsterConcept: 'two different small monsters equally exhausted side by side',
    iconPrompt: 'original cute collectible monster mascot, two different tiny exhausted creatures side by side, sleepy eyes, inclusive meme energy',
    memeNarrative: 'semua capek, beda cerita',
    description: 'same grind. different pressure.',
    acronym: 'Social Access for Mutual Advancement & Equality',
    mintAddress: 'REPLACE_WITH_SAMA2CAPEK_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_SAMA2CAPEK',
    requiredBalance: 1,
    accentColor: '#FF3A21',
    featureTitle: 'Inclusion Message Kit',
    featureDescription: 'Inclusive messaging and equality campaign framing helper.',
  },
  {
    id: 'sdg-6-ngocokin',
    symbol: 'NGOCOKIN',
    name: 'Ngocokin',
    sdgNumber: 6,
    sdgName: 'Clean Water and Sanitation',
    emoji: '💧',
    imagePath: '/tokens/ngocokin.png',
    category: 'SURVIVAL',
    monsterName: 'BocorBlob',
    monsterConcept: 'leaking water-bucket blob with duct tape patches and panic face',
    iconPrompt: 'original cute collectible monster mascot, leaking water bucket blob, duct tape patches, panic face, clean blue splash style',
    memeNarrative: 'air ada, tapi questionable 💀',
    description: 'hydration maybe. survival definitely.',
    acronym: 'Network for Global Open Clean Water Infrastructure',
    mintAddress: 'REPLACE_WITH_NGOCOKIN_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_NGOCOKIN',
    requiredBalance: 1,
    accentColor: '#26BDE2',
    featureTitle: 'Water Access Story Builder',
    featureDescription: 'Tool to explain clean water problems in simple public language.',
  },
  {
    id: 'sdg-7-lampumati',
    symbol: 'LAMPUMATI',
    name: 'Lampu Mati',
    sdgNumber: 7,
    sdgName: 'Affordable and Clean Energy',
    emoji: '🔌',
    imagePath: '/tokens/lampumati.png',
    category: 'WORK & BUILD',
    monsterName: 'BulbMati',
    monsterConcept: 'dead lightbulb creature with tiny candle and tangled cable arms',
    iconPrompt: 'original cute collectible monster mascot, dead lightbulb creature, tiny candle, tangled cable arms, funny dark energy',
    memeNarrative: 'listrik mati, semangat ikut mati',
    description: 'no energy. just darkness. still holding.',
    acronym: 'Local Access for Mutual Power & Utility Infrastructure',
    mintAddress: 'REPLACE_WITH_LAMPUMATI_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_LAMPUMATI',
    requiredBalance: 1,
    accentColor: '#FCC30B',
    featureTitle: 'Energy Awareness Mini Tool',
    featureDescription: 'Local clean energy and electricity access storytelling helper.',
  },
  {
    id: 'sdg-8-gajikapan',
    symbol: 'GAJIKAPAN',
    name: 'Gaji Kapan',
    sdgNumber: 8,
    sdgName: 'Decent Work and Economic Growth',
    emoji: '💼',
    imagePath: '/tokens/gajikapan.png',
    category: 'WORK & BUILD',
    monsterName: 'SlipKosong',
    monsterConcept: 'salary envelope creature holding empty payslip and payday calendar',
    iconPrompt: 'original cute collectible monster mascot, salary envelope creature, empty payslip, payday calendar, broke office meme',
    memeNarrative: 'kerja iya, income pending',
    description: 'working hard. wallet empty. classic combo.',
    acronym: 'Growth Access for Jobs & Inclusive Network',
    mintAddress: 'REPLACE_WITH_GAJIKAPAN_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_GAJIKAPAN',
    requiredBalance: 1,
    accentColor: '#A21942',
    featureTitle: 'DeGen CV / Resume Roaster',
    featureDescription: 'A playful work-readiness and resume improvement mock tool.',
  },
  {
    id: 'sdg-9-ngidea',
    symbol: 'NGIDEA',
    name: 'Nge-Idea',
    sdgNumber: 9,
    sdgName: 'Industry, Innovation, and Infrastructure',
    emoji: '🤖',
    imagePath: '/tokens/ngidea.png',
    category: 'WORK & BUILD',
    monsterName: 'IdeaGoblin',
    monsterConcept: 'tiny idea goblin with glowing lightbulb head, sticky notes, gears, sparks',
    iconPrompt: 'original cute collectible monster mascot, tiny idea goblin, glowing lightbulb head, sticky notes, gears, sparks',
    memeNarrative: 'banyak ide, zero execution',
    description: 'startup in mind. stuck in reality.',
    acronym: 'Network for Growth & Innovation Development',
    mintAddress: 'REPLACE_WITH_NGIDEA_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_NGIDEA',
    requiredBalance: 1,
    accentColor: '#FD6925',
    featureTitle: 'Idea-to-Pitch Generator',
    featureDescription: 'Turn chaotic ideas into structured early project pitches.',
  },
  {
    id: 'sdg-10-gakadil',
    symbol: 'GAKADIL',
    name: 'Gak Adil',
    sdgNumber: 10,
    sdgName: 'Reduced Inequalities',
    emoji: '⚖️',
    imagePath: '/tokens/gakadil.png',
    category: 'SOCIETY',
    monsterName: 'MiringMon',
    monsterConcept: 'extremely tilted scale creature with unfair-system expression',
    iconPrompt: 'original cute collectible monster mascot, extremely tilted scale creature, unfair-system expression, expressive pink glow',
    memeNarrative: 'hidup beda difficulty',
    description: 'easy mode vs nightmare mode. guess where we are.',
    acronym: 'Global Access for Anti-Disparity Inclusive Living',
    mintAddress: 'REPLACE_WITH_GAKADIL_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_GAKADIL',
    requiredBalance: 1,
    accentColor: '#DD1367',
    featureTitle: 'Equity Framing Assistant',
    featureDescription: 'A tool for mapping inclusion and inequality narratives.',
  },
  {
    id: 'sdg-11-rumahpanas',
    symbol: 'RUMAHPANAS',
    name: 'Rumah Panas',
    sdgNumber: 11,
    sdgName: 'Sustainable Cities and Communities',
    emoji: '🏚️',
    imagePath: '/tokens/rumahpanas.png',
    category: 'SOCIETY',
    monsterName: 'RumahGosong',
    monsterConcept: 'tiny sweating house creature with hot roof and broken fan',
    iconPrompt: 'original cute collectible monster mascot, tiny sweating house creature, hot roof, broken fan, orange heat haze',
    memeNarrative: 'rumah kecil, panas maksimal',
    description: 'urban life but make it suffer. still vibing tho.',
    acronym: 'Resilient Urban Mobility & Housing Access Sustainability',
    mintAddress: 'REPLACE_WITH_RUMAHPANAS_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_RUMAHPANAS',
    requiredBalance: 1,
    accentColor: '#FD9D24',
    featureTitle: 'Urban Issue Mapper',
    featureDescription: 'Helps frame city, housing, and community problems.',
  },
  {
    id: 'sdg-12-belilagi',
    symbol: 'BELILAGI',
    name: 'Beli Lagi',
    sdgNumber: 12,
    sdgName: 'Responsible Consumption and Production',
    emoji: '🛍️',
    imagePath: '/tokens/belilagi.png',
    category: 'PLANET',
    monsterName: 'CheckoutGremlin',
    monsterConcept: 'guilty shopping-bag gremlin with long receipt tail and glowing checkout button',
    iconPrompt: 'original cute collectible monster mascot, guilty shopping bag gremlin, long receipt tail, glowing checkout button',
    memeNarrative: 'gak butuh, tetap checkout',
    description: 'retail therapy hits hard. regret comes later.',
    acronym: 'Balanced Economic Loop & Lifecycle Impact',
    mintAddress: 'REPLACE_WITH_BELILAGI_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_BELILAGI',
    requiredBalance: 1,
    accentColor: '#BF8B2E',
    featureTitle: 'Consumption Reflection Tool',
    featureDescription: 'A playful way to reflect on consumption and waste habits.',
  },
  {
    id: 'sdg-13-bumipanas',
    symbol: 'BUMIPANAS',
    name: 'Bumi Panas',
    sdgNumber: 13,
    sdgName: 'Climate Action',
    emoji: '🔥',
    imagePath: '/tokens/bumipanas.png',
    category: 'PLANET',
    monsterName: 'BumiDemam',
    monsterConcept: 'sweating Earth creature with pixel sunglasses, small flame, and thermometer',
    iconPrompt: 'original cute collectible monster mascot, sweating Earth creature, pixel sunglasses, small flame, thermometer, climate meme',
    memeNarrative: 'neraka versi beta testing',
    description: 'planet collapsing. still scrolling.',
    acronym: 'Building Up Mutual Initiative for Planetary Sustainability',
    mintAddress: 'REPLACE_WITH_BUMIPANAS_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_BUMIPANAS',
    requiredBalance: 1,
    accentColor: '#3F7E44',
    featureTitle: 'Eco-Carbon Offset Calculator',
    featureDescription: 'Mock climate calculator and climate action storytelling tool.',
  },
  {
    id: 'sdg-14-ikanminggir',
    symbol: 'IKANMINGGIR',
    name: 'Ikan Minggir',
    sdgNumber: 14,
    sdgName: 'Life Below Water',
    emoji: '🐟',
    imagePath: '/tokens/ikanminggir.png',
    category: 'PLANET',
    monsterName: 'FishCabut',
    monsterConcept: 'cute fish creature carrying suitcase and leaving messy ocean trail',
    iconPrompt: 'original cute collectible monster mascot, cute fish creature carrying suitcase, messy ocean trail, blue aquatic glow',
    memeNarrative: 'laut rusak, ikan cabut',
    description: "ocean dying. we pretending it's fine.",
    acronym: 'Inclusive Komunitas Access for Marine Integrity & Growth',
    mintAddress: 'REPLACE_WITH_IKANMINGGIR_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_IKANMINGGIR',
    requiredBalance: 1,
    accentColor: '#0A97D9',
    featureTitle: 'Ocean Campaign Card',
    featureDescription: 'Generate simple public narratives for marine and ocean issues.',
  },
  {
    id: 'sdg-15-hutanhilang',
    symbol: 'HUTANHILANG',
    name: 'Hutan Hilang',
    sdgNumber: 15,
    sdgName: 'Life on Land',
    emoji: '🌲',
    imagePath: '/tokens/hutanhilang.png',
    category: 'PLANET',
    monsterName: 'TunggulTiny',
    monsterConcept: 'tiny tree-stump creature with one last leaf and roots as feet',
    iconPrompt: 'original cute collectible monster mascot, tiny tree stump creature, one last leaf, roots as feet, green forest glow',
    memeNarrative: 'pohon ilang, panas datang',
    description: 'deforestation speedrun. nature losing.',
    acronym: 'Holistic Upland Terraforming & Nature Access Network',
    mintAddress: 'REPLACE_WITH_HUTANHILANG_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_HUTANHILANG',
    requiredBalance: 1,
    accentColor: '#56C02B',
    featureTitle: 'Biodiversity Story Tool',
    featureDescription: 'Explain land, forest, and biodiversity issues in relatable language.',
  },
  {
    id: 'sdg-16-diperiksa',
    symbol: 'DIPERIKSA',
    name: 'Diperiksa',
    sdgNumber: 16,
    sdgName: 'Peace, Justice, and Strong Institutions',
    emoji: '🚔',
    imagePath: '/tokens/diperiksa.png',
    category: 'SOCIETY',
    monsterName: 'LampuSidang',
    monsterConcept: 'nervous document creature under interrogation lamp with flying papers',
    iconPrompt: 'original cute collectible monster mascot, nervous document creature under interrogation lamp, flying papers, blue civic noir',
    memeNarrative: 'bro dipanggil, gak bisa nolak',
    description: 'justice system loading… error 404.',
    acronym: 'Development for Inclusive Peace & Institutional Support',
    mintAddress: 'REPLACE_WITH_DIPERIKSA_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_DIPERIKSA',
    requiredBalance: 1,
    accentColor: '#00689D',
    featureTitle: 'Civic Explainer',
    featureDescription: 'Civic literacy and institutional trust explainer tool.',
  },
  {
    id: 'sdg-17-barbarga',
    symbol: 'BARBARGA',
    name: 'Bar Bar Tapi Kerja Sama',
    sdgNumber: 17,
    sdgName: 'Partnerships for the Goals',
    emoji: '🤝',
    imagePath: '/tokens/barbarga.png',
    category: 'SOCIETY',
    monsterName: 'ChaosCrew',
    monsterConcept: 'chaotic crew of cute original monsters high-fiving with mismatched puzzle pieces',
    iconPrompt: 'original cute collectible monster mascot crew, high-fiving chaotic cute monsters, mismatched puzzle pieces, team energy',
    memeNarrative: 'chaos sendiri mati, chaos bareng survive',
    description: 'alone weak. together still chaotic.',
    acronym: 'Building Alliance & Resource Bridge for Growth',
    mintAddress: 'REPLACE_WITH_BARBARGA_MINT',
    pumpFunLink: 'https://pump.fun/REPLACE_WITH_BARBARGA',
    requiredBalance: 1,
    accentColor: '#19486A',
    featureTitle: 'Partnership Canvas',
    featureDescription: 'Simple collaboration canvas for impact partnerships.',
  },
];

export function getTokenBySdg(sdgNumber: number) {
  return SDEGEN_TOKENS.find((token) => token.sdgNumber === sdgNumber);
}
